#
# buildspec.yml
#

version: 0.2

#env:
#  variables:

phases:
  install:
    runtime-versions:
      nodejs: 18
#    commands:

  pre_build:
    commands:
      - git clone https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/uvalib/dcmd/modern-library-bibliography.git
      - ln -s modern-library-bibliography/MSWord .
      - ln -s modern-library-bibliography/TransmogXML .

  build:
    commands:
      - npm install -g yarn
      - yarn install
      - yarn run build
      - echo "Syncing s3://${S3_BUCKET}"
      - aws s3 sync build s3://${S3_BUCKET} --delete --quiet
      - echo "Invalidating CDN cache"
      - AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"

#  post_build:
#    commands:

#
# end of file
#
